version: '3.9'

services:
  evently.api2:
    image: ${DOCKER_REGISTRY-}eventlyapi
    container_name: Evently.api2
    build:
      context: .
      dockerfile: Evently.Api/Dockerfile
    ports:
        - 5000:8080
        - 5001:8081 
        
  evently.database:
    image: postgres:latest
    container_name: Evently.Database
    environment:    
        - POSTGRES_USER=eventlyuser
        - POSTGRES_PASSWORD=EventlyPassword123!
        - POSTGRES_DB=eventlydb
    ports:
        - 5432:5432 